import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts ./src/servicios`.

export type Estantes = Models.Row & {
  nombre: string;
  secciones: Secciones[];
}

export type Galpones = Models.Row & {
  nombre: string;
  estantes: Estantes[];
}

export type Secciones = Models.Row & {
  Nombre: string;
  cajones: Cajones[];
}

export type Cajones = Models.Row & {
  nombre: string;
}

export type Producto = {
  $id: string;
  nombre: string;
  codigo: string;
  descripcion: string | null;
  pesoUnitario: number | null;
  grupo: string;
  fabricante: string;
}

export type Grupo = IdNombre & { }

export type Fabricante = IdNombre & { }

export type Inventario = Models.Row & {
  cajon: Cajones;
  producto: Producto;
  cantidad: number;
}

export type Movimientos = Models.Row & {
  producto: Producto;
  cantidad: number;
  almacenista: Almacenista;
}

export type Almacenista = IdNombre & { }

export type IdNombre = {
  $id: string;
  nombre: string;
}
