import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts ./src/servicios`.

export type Estantes = Models.Row & {
  nombre: string;
  secciones: Secciones[];
}

export type Galpones = Models.Row & {
  nombre: string;
  estantes: Estantes[];
}

export type Secciones = Models.Row & {
  Nombre: string;
  cajones: Cajones[];
}

export type Cajones = Models.Row & {
  nombre: string;
}

export type Productos = Models.Row & {
  nombre: string;
  codigo_serial: string;
  detalles: string | null;
  pesoUnitario: number | null;
  grupo: Grupos;
  fabricante: Fabricantes;
}

export type Grupos = Models.Row & {
  nombre: string;
}

export type Fabricantes = Models.Row & {
  nombre: string;
}

export type Inventario = Models.Row & {
  cajon: Cajones;
  producto: Productos;
  cantidad: number;
}

export type Movimientos = Models.Row & {
  producto: Productos;
  cantidad: number;
  almacenista: Almacenistas;
}

export type Almacenistas = Models.Row & {
  nombre: string;
}

export type IdNombre = {
  $id: string;
  nombre: string;
}
